"""
LaTeX to PDF conversion utilities.
"""

import subprocess
from pathlib import Path
from typing import Optional, Tuple, Union


def compile_latex_to_pdf(tex_file: Path, output_dir: Optional[Path] = None) -> Tuple[bool, Union[Path, str]]:
    """
    Compile a .tex file to PDF using pdflatex.
    Runs twice for proper references and TOC.
    """
    work_dir = tex_file.parent
    
    if output_dir:
        output_dir.mkdir(parents=True, exist_ok=True)
        pdf_path = output_dir / (tex_file.stem + ".pdf")
        output_args = [f"-output-directory={output_dir}"]
    else:
        pdf_path = work_dir / (tex_file.stem + ".pdf")
        output_args = []
    
    cmd = [
        "pdflatex",
        "-interaction=nonstopmode",
        "-halt-on-error",
        "-file-line-error",
        *output_args,
        str(tex_file.name)
    ]
    
    try:
        # Run pdflatex twice for references/TOC
        for run in range(2):
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                cwd=str(work_dir),
                timeout=180
            )
        
        # Check the correct location for PDF
        if output_dir:
            check_path = output_dir / (tex_file.stem + ".pdf")
        else:
            check_path = work_dir / (tex_file.stem + ".pdf")
        
        if check_path.exists():
            return True, check_path
        else:
            # Try to extract error
            log_file = (output_dir or work_dir) / (tex_file.stem + ".log")
            error_msg = "PDF not generated"
            if log_file.exists():
                log_content = log_file.read_text(errors='ignore')
                for line in log_content.split('\n'):
                    if line.startswith('!') or 'Error' in line:
                        error_msg = line[:100]
                        break
            return False, error_msg
            
    except subprocess.TimeoutExpired:
        return False, "Compilation timed out (>3 minutes)"
    except Exception as e:
        return False, str(e)


def clean_latex_auxiliary_files(tex_file: Path, output_dir: Optional[Path] = None):
    """Remove auxiliary files generated by LaTeX compilation."""
    base_name = tex_file.stem
    work_dir = output_dir or tex_file.parent
    
    aux_extensions = [
        '.aux', '.log', '.out', '.toc', '.lof', '.lot', 
        '.fls', '.fdb_latexmk', '.synctex.gz', '.nav', 
        '.snm', '.vrb', '.bbl', '.blg'
    ]
    
    for ext in aux_extensions:
        aux_file = work_dir / (base_name + ext)
        if aux_file.exists():
            try:
                aux_file.unlink()
            except:
                pass
